Update word-exclusion

diff --git a/.github/workflows/word-exclusion.yml b/.github/workflows/word-exclusion.yml
--- a/.github/workflows/word-exclusion.yml
+++ b/.github/workflows/word-exclusion.yml
@@ -3,10 +3,10 @@ name: Word Exclusion
 on:
   push:
     branches:
-      - 'main'
+      - 'testing'
   pull_request_target:
     branches:
-      - 'main'
+      - 'testing'
 
 jobs:
   word_exclusion:
@@ -21,120 +21,136 @@ jobs:
           sudo dpkg -i packages-microsoft-prod.deb
           sudo apt-get update
           sudo apt-get install -y powershell
-
-      - name: Get directory paths from .gitattributes
+ 
+    
+      - name: Get file list from .gitattributes in tmo-main branch
+        id: get_file_list
         run: |
-          directories=$(tail -n +18 .gitattributes | awk '{print $1}' | grep -v -E '^\s*#|merge=ours')
-          echo "::set-output name=directories::$directories"
+          git show origin/testing:.gitattributes > gitattributes_temp.txt
+          echo "Content of gitattributes_temp.txt:"
+          Get-Content -Path gitattributes_temp.txt
+          $FileList = Get-Content -Path gitattributes_temp.txt |
+                      Select-Object -Skip 17 |
+                      Select-String -Pattern '^(.*?)(?=\smerge=ours|$)' |
+                      ForEach-Object { $_.Matches.Groups[1].Value }
 
-      - name: Run Word Search script
-        run: |
-          $WordList = @("*private*", "*pet*", "*tracker*") # Add the words you want to find here
-          $Matches = @()
+          echo "Content of the extracted file list:"
+          $FileList
 
-          # Read the .gitattributes file starting from line 18
-          $GitAttributes = Get-Content -Path .gitattributes | Select-Object -Skip 17
-
-          # Extract directories and files from .gitattributes using regex
-          $Directories = $GitAttributes -match '^(\S+\/?)\s+(-?)(?!\s*#)'
-
-          foreach ($Directory in $Directories) {
-            $Directory = $Directory.Trim()
-
-            if (Test-Path $Directory) {
-              Get-ChildItem -Path $Directory -Recurse -Include "*" -File | ForEach-Object {
-                $FileName = $_.FullName
-
-                foreach ($Word in $WordList) {
-                  if (Select-String -Path $FileName -Pattern $Word -Quiet) {
-                    $Matches += New-Object PSObject -Property @{
-                      Directory = $Directory
-                      Match = $Word
-                      File = $FileName
-                    }
-                  }
-                }
-              }
-            }
+          if ($FileList.Count -eq 0) {
+            echo "No files were extracted from .gitattributes. Check the pattern or file content."
+            exit 1
           }
-
-          if ($Matches.Count -gt 0) {
-            echo "Found matches for the following words: $($Matches | ForEach-Object { $_.Match })"
-            exit 1 # This will cause the script to exit with an error code, stopping the pipeline.
-          } else {
-            echo "No matches found. Proceeding with the pipeline."
-          }
-
-          $Matches | ConvertTo-Json -Depth 100 | Out-File matches.json
-        env:
-          DIRECTORIES: ${{ steps.GetDirectories.outputs.directories }}
+          $FileList | Out-File -Encoding utf8 file_list.txt
         shell: pwsh
 
-      - name: Get modified files and folders
-        id: changes
-        run: |
-          # Fetch the commit hash of the latest commit on the main branch
-          commit_hash=$(git rev-parse origin/main)
-          # Get the list of modified files and folders between the current branch and main branch
-          modified_files_folders=$(git diff --name-only $commit_hash HEAD)
-          echo "::set-output name=modified::$modified_files_folders"
-
       - name: Run Word Exclusion script
-        if: steps.changes.outputs.modified != ''
         run: |
-          $WordList = @("*private*", "*pet*", "*tracker*") # Add the words you want to find here
-          $WordExcludeList = @("snippet") # Add words to exclude from search
+          $Patterns = @("^(private)$", "^(tracker)", "^(pets)")
+          $PathToCheck = $env:GITHUB_WORKSPACE
           $Matches = @()
 
-          $ModifiedItems = $env:MODIFIED_ITEMS -split "`n"
+          # Get the list of changed files (for PR) or the list of all files (for push) in the current directory
+          $ChangedFiles = Get-ChildItem -Path $PathToCheck | ForEach-Object { $_.FullName }
 
-          Get-ChildItem -Path $ModifiedItems -Recurse | ForEach-Object {
-              $Type = if ($_.PSIsContainer) { "dir" } else { "file" }
-              $Name = $_.FullName
+          # Read the list of files to check from file_list.txt
+          $FileList = Get-Content file_list.txt
 
-              foreach ($Pattern in $WordList) {
-                  if ($WordExcludeList -notcontains $Pattern) {
-                      if ($Name -like "*$Pattern*") {
+          # Find matches in directory names and file names for changed files
+          $ChangedFiles | ForEach-Object {
+              $Type = if (Test-Path $_ -PathType Container) { "dir" } else { "filename" }
+              $Name = $_
+              foreach ($Pattern in $Patterns) {
+                  if ($Name -match $Pattern) {
+                      $Matches += New-Object PSObject -Property @{
+                          Type = $Type
+                          Match = $Pattern
+                          Name = $Name
+                      }
+                      break  # Exit the loop once a match is found
+                  }
+              }
+          }
+
+          # Find matches in file contents for changed files
+          $ChangedFiles | ForEach-Object {
+              $FileName = $_
+              foreach ($Pattern in $Patterns) {
+                  if (Select-String -Path $FileName -Pattern $Pattern -Quiet) {
+                      $Matches += New-Object PSObject -Property @{
+                          Type = "file"
+                          Match = $Pattern
+                          Name = $FileName
+                      }
+                      break  # Exit the loop once a match is found
+                  }
+              }
+          }
+
+          # Find matches in directory names and file names for files to check from file_list.txt
+          $NotFoundPaths = @()
+          $FileList | ForEach-Object {
+              $Type = if (Test-Path $_ -PathType Container) { "dir" } else { "filename" }
+              $Name = $_
+              foreach ($Pattern in $Patterns) {
+                  try {
+                      # Attempt to check if the path exists in the current directory
+                      if ($Name -match $Pattern) {
                           $Matches += New-Object PSObject -Property @{
                               Type = $Type
                               Match = $Pattern
                               Name = $Name
                           }
+                          break  # Exit the loop once a match is found
                       }
+                  }
+                  catch {
+                      # Add the path to the list of not found paths if it doesn't exist in the current directory
+                      $NotFoundPaths += $Name
+                      break  # Exit the loop once a match is found
                   }
               }
           }
 
-          Get-ChildItem -Path $ModifiedItems -Recurse -File | ForEach-Object {
-              $FileName = $_.FullName
-
-              foreach ($Pattern in $WordList) {
-                  if ($WordExcludeList -notcontains $Pattern) {
+          # Find matches in file contents for files to check from file_list.txt
+          $FileList | ForEach-Object {
+              $FileName = $_
+              foreach ($Pattern in $Patterns) {
+                  try {
+                      # Attempt to check if the file exists in the current directory
                       if (Select-String -Path $FileName -Pattern $Pattern -Quiet) {
                           $Matches += New-Object PSObject -Property @{
                               Type = "file"
                               Match = $Pattern
                               Name = $FileName
                           }
+                          break  # Exit the loop once a match is found
                       }
+                  }
+                  catch {
+                      # Add the file path to the list of not found paths if it doesn't exist in the current directory
+                      $NotFoundPaths += $FileName
+                      break  # Exit the loop once a match is found
                   }
               }
           }
-          
-          if ($Matches.Count -gt 0) {
-            echo "Found matches for the following words: $($Matches | ForEach-Object { $_.Match })"
-            exit 1 # This will cause the script to exit with an error code, stopping the pipeline.
-          } else {
-            echo "No matches found in modified files. Proceeding with the pipeline."
+
+          # Save matches to a variable
+          $MatchedItems = $Matches
+
+          # Output matches
+          $MatchedItems
+
+          # Output paths that were not found in the main branch
+          Write-Output "Paths not found in the main branch:"
+          $NotFoundPaths
+
+          # Fail the pipeline if matches were found
+          if ($MatchedItems.Count -gt 0) {
+            Write-Host "Found matches. Pipeline will fail."
+            $MatchedItems | ForEach-Object {
+              Write-Host $_
+            }
+            exit 1
           }
-
-          $Matches | ConvertTo-Json -Depth 100 | Out-File matches.json
-        env:
-          MODIFIED_ITEMS: ${{ steps.changes.outputs.modified }}
-        shell: pwsh
-
-      - name: Upload JSON output
-        uses: actions/upload-artifact@v2
-        with:
-          name: matches
-          path: matches.json
+        shell: pwsh  # Use the PowerShell shell to execute the script
